"use client"
import "../styles/globals.css"
import { QueryClient,QueryClientProvider } from 'react-query';
import {SessionProvider}from "next-auth/react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
  const queryClient= new QueryClient()
 return (
    <html lang="en">
      <SessionProvider>
<QueryClientProvider client={queryClient}>
      <body>{children}</body>
</QueryClientProvider>
</SessionProvider>
    </html>
  )
}
